version: '3.8'

services:
  backend:
    build: ./care-connect-backend
    ports:
      - "5000:5000"
    env_file:
      - ./care-connect-backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./care-connect-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./care-connect-frontend:/app           
      - /app/node_modules                      
    environment:
      - CHOKIDAR_USEPOLLING=true            

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: